apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: monitoring
data:
  kibana.yml: |
    server.host: "0.0.0.0"
    server.shutdownTimeout: "5s"
    
    # Elasticsearch connection
    elasticsearch.hosts: [ "http://elasticsearch:9200" ]
    elasticsearch.username: "kibana_system"
    
    # Monitoring
    monitoring.ui.container.elasticsearch.enabled: true
