server.host: "0.0.0.0"
server.shutdownTimeout: "5s"

# Elasticsearch connection
elasticsearch.hosts: [ "http://elasticsearch:9200" ]
elasticsearch.username: "kibana_system"
elasticsearch.password: "${KIBANA_SYSTEM_PASSWORD}"

# Security and Encryption
xpack.encryptedSavedObjects.encryptionKey: "${XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY}"
xpack.security.encryptionKey: "${XPACK_SECURITY_ENCRYPTIONKEY}"
xpack.reporting.encryptionKey: "${XPACK_REPORTING_ENCRYPTIONKEY}"

# Monitoring
monitoring.ui.container.elasticsearch.enabled: true
